const express = require('express');
const passport = require('passport');
const { createCompany, getCompany, getCompanybyid, deleteCompany, updateCompany } = require('../Controllers/CompanyAPI');
const router = express.Router();
router.post('/createCompany', passport.authenticate('bearer', { session: false }), createCompany);
router.get('/getCompany', passport.authenticate('bearer', { session: false }), getCompany);
router.get('/getCompanybyid/:idCompany', passport.authenticate('bearer', { session: false }), getCompanybyid);
router.put('/updateCompany/:idCompany', passport.authenticate('bearer', { session: false }), updateCompany);
router.delete('/deleteCompany/:idCompany', passport.authenticate('bearer', { session: false }), deleteCompany);
module.exports = router;